__author__ = 'Roni'

MRI = True
if(MRI):
    SCREEN_DISTANCE_IN_CM = 120
    SCREEN_RESOLUTION = (1920, 1080)
    SCREEN_WIDTH_IN_CM = 29.5
else:
    SCREEN_WIDTH_IN_CM = 29.5
    SCREEN_DISTANCE_IN_CM = 50
    SCREEN_RESOLUTION = (1440, 900)

STIMULI_SIZE = [6, 1.5]
END_TRIAL_DELAY = 1
BEGIN_TRIAL_DELAY = 1
RESPONSE_KEY = 'r'
